export const endpoints = {
  TEKNISKBACKEND: 'https://tekniskback.azurewebsites.net',
  ENDGAME: 'endGame',
  CLASSIFY: 'classify',
  GETLABEL: 'getLabel',
  STARTGAME: 'startGame',
  AUTH: 'auth',
  ADMIN: 'admin',
  DROPTABLE: 'dropTable',
  TRAINML: 'trainML',
  CLEARTRAINSET: 'clearTrainSet',
  PING: 'ping',
  GETSTATUS: 'get_status',
  LOGOUT: 'logout',
};
