name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Checkout master
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build:ci

      - name: Login to Azure
        uses: azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure
        uses: azure/CLI@v1
        with:
          inlinescript: az storage blob upload-batch --account-name frontwebstorage --account-key ${{ secrets.AZURE_ACCOUNT_KEY }} --source dist/tekniskmuseum --destination '$web'

      - name: Set cut-off date
        run: |
          export DATE=`date --date="1 day ago" +%Y-%m-%dT%H:%MZ`
          echo "::set-env name=DATE::$DATE"

      - name: Azure delete old js and css
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob delete-batch --source '$web' --account-name frontwebstorage --pattern "*.js" --if-unmodified-since $DATE --account-key ${{ secrets.AZURE_ACCOUNT_KEY }}
            az storage blob delete-batch --source '$web' --account-name frontwebstorage --pattern "*.css" --if-unmodified-since $DATE --account-key ${{ secrets.AZURE_ACCOUNT_KEY }}

